### ISSUE TITLE
Cannot clone cloud9

### ISSUE THREAD

**Issue by fithisux** [sourcemint/pm-sm#2]
With node 0.6.16 it somehow installed but with errors. But I cannot clone cloud9 (it is also not mentioned that git should be in the path) 

D:\winoss\langs\nodejs>sm clone --dev https://github.com/ajaxorg/cloud9/tree/mas
ter cloud9
Cloning 'git@github.com:ajaxorg/cloud9.git' to 'd:\winoss\langs\nodejs.sourcemi
nt\repository-cache\git\github.com\ajaxorg\cloud9.git'.
Cloning into 'cloud9.git'...
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
- ERROR **********************************************************************
  *****
- Error: Git error: Cloning into 'cloud9.git'...
  Permission denied (publickey).
  fatal: The remote end hung up unexpectedly
- File : false @ false
- Stack:
-    Error: Git error: Cloning into 'cloud9.git'...
-    Permission denied (publickey).
-    fatal: The remote end hung up unexpectedly
  *
-        at ChildProcess.<anonymous> (D:\winoss\langs\nodejs\node_modules\sm\n
  ode_modules\sourcemint-pm-sm\node_modules\sourcemint-pm-git\lib\git.js:370:29)
-        at ChildProcess.emit (events.js:70:17)
-        at maybeExit (child_process.js:362:16)
-        at Process.onexit (child_process.js:398:5)
- ERROR **********************************************************************
  *****

We had an error cloning.
Try re-cloning which the -d flag to delete the target directory first (or delete
 yourself and try again).
If cloning keeps failing due to GIT errors you need to resolve these. Like setti
ng up SSH for accessing github.
If cloning seems to fail due to a corrupt git repository or `sm` or `npm` error
you can wipe the install cache (~/.sourcemint/*-cache) and try again.
If problems persist email your clone URL to the mailing list for support (must b
e publicly accessible): http://groups.google.com/group/sourcemint

**Comment by cadorn** [comment]
`sm` currently does not work on windows.

If you try on unix drop the `--dev` and use `--install` instead to not clone it in write mode if you do not have access to the repository.

**Comment by rmariuzzo** [comment]
I think it should be explained too in the main `README.md` file. Anyway, thanks. Changing the parameter from `--dev` to `--install` do the trick.
